# Generated by Django 5.0.1 on 2024-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DIM_BU",
            fields=[
                (
                    "bu_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("BusinessUnit", models.CharField(max_length=255)),
                ("Category", models.CharField(max_length=255)),
                ("ProductLine", models.CharField(max_length=255)),
                ("part_type_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "DIM_BU",
                "managed": False,
            },
        ),
    ]
