# Generated by Django 5.0.1 on 2024-07-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PiesDev",
            fields=[
                ("brand_aaia_id", models.CharField(max_length=255)),
                ("brand_name", models.CharField(max_length=255, null=True)),
                (
                    "sub_brand_aaia_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sub_brand_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("part_type_name", models.CharField(max_length=255)),
                ("brand_owner", models.CharField(max_length=255, null=True)),
                ("brand_owner_name", models.CharField(max_length=255, null=True)),
                ("part_number", models.CharField(max_length=255)),
                ("aces_applications", models.TextField(blank=True, null=True)),
                ("piesID", models.IntegerField(primary_key=True, serialize=False)),
                ("brand_id", models.CharField(max_length=255, null=True)),
                ("bu_id", models.CharField(max_length=255)),
                ("BusinessUnit", models.CharField(max_length=255)),
                ("Category", models.CharField(max_length=255)),
                ("ProductLine", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "pies_dev",
                "managed": False,
            },
        ),
    ]
